[build]
target = "x86_64-pc-windows-msvc"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"  # Optimiser pour la taille

# Configuration for cross-compiling to Linux
[target.x86_64-unknown-linux-gnu]
linker = "/home/zehelh/zig_cc_wrapper.sh" # Utiliser le script wrapper
rustflags = ["-C", "target-feature=+crt-static"]

# Vous pourriez avoir besoin de spécifier où trouver les bibliothèques système pour la cible.
# Consultez la documentation Cargo pour plus de détails sur la configuration de build.